# Generated by Django 4.1.5 on 2023-02-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tematica', models.CharField(max_length=10)),
                ('estudio', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('texto', models.TextField()),
                ('fecha', models.DateField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misjuegos.juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misjuegos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_pub', models.DateField()),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misjuegos.reseña')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misjuegos.usuario')),
            ],
        ),
    ]
